### ISSUE TITLE
Exception when use httpClient.addResponseModifier after upgrade from getx 4.1.4

### ISSUE THREAD

**Issue by amer-zk** [jonataslaw/getx#1720]
**Describe the bug**
After I upgrade my getx from 4.1.4 to 4.3.4

Exception throws whenever I use this code : 

    httpClient.addResponseModifier<dynamic>((request, response) {
      print(response.bodyString);
    });

**Reproduction code

this will produce exception : 
Api().checkAuth();

example:

```dart
void main() => runApp(MaterialApp(home: Home()));

class Home extends StatelessWidget {
  final count = 0.obs;
  @override
  Widget build(context) => Scaffold(
      appBar: AppBar(title: Text("counter")),
      body: Center(
        child: Obx(() => Text("$count")),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () => Api().checkAuth(),
      ));
}

class Api extends GetConnect {
  String? baseUrl = '*******';
  Api() {
    baseUrl = this.baseUrl;

    httpClient.addResponseModifier<dynamic>((request, response) {
      print(response.bodyString);
    });
   }


  dynamic getData(Response<dynamic> ret) {
    return ret.body?['data'];
  }

  Future<User> checkAuth() async {
    Map<String, dynamic> query = {
      'version_code': 1,
    };
    var ret = await get("/check_auth",query: query);
    return User.fromJson(getData(ret));
  }
}
```

**To Reproduce**
1. open the app
2. Click on floatingActionButton
3. open log and see exception says : 
VERBOSE-2:ui_dart_state.cc(199)] Unhandled Exception: NoSuchMethodError: The getter 'statusCode' was called on null.
Receiver: null
Tried calling: statusCode
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
#1      GetHttpClient._performRequest (package:get/get_connect/http/src/http.dart:211:50)
<asynchronous suspension>
#2      GetHttpClient.get (package:get/get_connect/http/src/http.dart:452:22)
<asynchronous suspension>
#3      Api.checkAuth (package:first_flutter_app/Api.dart:180:15)
<asynchronous suspension>

**Expected behavior**
expected to print the response of the request (checkAuth) in the log 

**Flutter Version:**
Flutter 2.2.2 • channel stable •

**Getx Version:**
4.3.4

**Describe on which device you found the bug:**
ex: iPhone 11 pro . iOS 13.7.

**Comment by jonataslaw** [comment]
```dart
 httpClient.addResponseModifier<dynamic>((request, response) {
      print(response.bodyString);
     return response; // you need return a response
    });
```
