### ISSUE TITLE
[Flutter : 3.13.0] Delay in deleting the controller on going back

### ISSUE THREAD

**Issue by deepss1** [jonataslaw/getx#2883]
**Describe the bug**
After a recent update to Flutter 3.13.0, the controllers do not get deleted until the screen is scrolled.
Due to which I have to manage some screens (which can be opened up from the list view) with a tag or else it gives an error saying that the controller was not found.

**Reproduction code
Will share it later today / tomorrow

**To Reproduce**
1. Create a list view
2. Create a details screen which shows index of the list item from a controller
3. Navigate to the details screen by taping on a item in ListView
4. Come back to the list view and without scrolling open another item

You will notice that it still shows the old item

**Expected behavior**
The screen should open with a fresh controller with updated values

**Flutter Version:**
3.13.0

**Getx Version:**
4.6.5

**Describe on which device you found the bug:**
Pixel 6A, Android 14

**Minimal reproduce code**
Will share it later today / tomorrow

**Comment by inyong1** [comment]
related
https://github.com/jonataslaw/getx/issues/2873

**Comment by deepss1** [comment]
@jonataslaw 

The issue seems to have resolved.

However, on the master branch, the dialogs, snackbars and bottomsheets do not close using `Get.back` if not opened using `Get.bottomSheet`

**Comment by laeo** [comment]
@jonataslaw  Can we receive a hot fix based on latest release version 4.6.5?

**Comment by nachtien** [comment]
I'm pretty new to flutter so don't judge please :) 

I think i might be running into a similar issue with this. I am using `FocusNode`s. When I navigate back from a screen with the `FocusNode`s, then forward to the page again with the `FocusNode`s, I'm getting the error:

`A FocusNode was used after being disposed`

The controller looks like this:

```dart
class FooController extends GetxController {

  final foo = FocusNode();

  @override
  void onClose() {
    foo.dispose();
    super.onClose();
  }
}
```

Navigating backwards I'm calling `Get.back()`. 

I'm also on Flutter 3.13.0.

**Comment by inyong1** [comment]
> @jonataslaw Can we receive a hot fix based on latest release version 4.6.5?

up. need hot fix in v 4.6.5 too @jonataslaw

**Comment by LianYangCn** [comment]
Any workaround?

**Comment by LianYangCn** [comment]
I found a workaround, which is to directly pull dependencies from a Git repository in the "pubspec.yaml" file,

```YAML
  get:
    git:
      url: https://github.com/jonataslaw/getx.git
```

Then I made some(huge) adjustments.

It's working fine.

**Comment by iamevaristus** [comment]
> **Describe the bug** After a recent update to Flutter 3.13.0, the controllers do not get deleted until the screen is scrolled. Due to which I have to manage some screens (which can be opened up from the list view) with a tag or else it gives an error saying that the controller was not found.
> 
> **Reproduction code Will share it later today / tomorrow
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Create a list view
> 2. Create a details screen which shows index of the list item from a controller
> 3. Navigate to the details screen by taping on a item in ListView
> 4. Come back to the list view and without scrolling open another item
> 
> You will notice that it still shows the old item
> 
> **Expected behavior** The screen should open with a fresh controller with updated values
> 
> **Flutter Version:** 3.13.0
> 
> **Getx Version:** 4.6.5
> 
> **Describe on which device you found the bug:** Pixel 6A, Android 14
> 
> **Minimal reproduce code** Will share it later today / tomorrow

I am facing the same issue here, started after I upgraded to flutter 3.13.

Description:
Say I have two screens/pages, the first one is called home, while the second one is product.
If I move from home to product, the product controller is created and initialized.
However, if I go back to home, the product controller is not deleted.
But if I go to product again, after going back to home, it returns the state of product page which was not deleted, and then deletes the product controller.

Need a fix on this issue as the app am working on is set to be launched on September.

**Comment by laeo** [comment]
> Moving to master, the navigation's animation became very slow.
> 
>  Android.Emulator.-.Pixel_2_API_34_5554.2023-08-29.16-12-18.mp4 
> compared to before, but with the controller not disposing on page close.
> 
>  Android.Emulator.-.Pixel_2_API_34_5554.2023-08-29.16-13-59.mp4

Same issue to me, did you find any solutions?

**Comment by M1sakii** [comment]
![image](https://github.com/jonataslaw/getx/assets/41244714/c57d46ac-d04d-4de7-b462-2174125fe00c)
Temporarily commenting these two lines of code solves this problem, then wait for the author to upgrade。

**Comment by M1sakii** [comment]
> > 移动到母版，导航的动画变得非常慢。
> > Android.Emulator.-.Pixel_2_API_34_5554.2023-08-29.16-12-18.mp4与以前相比，但控制器不会在页面关闭时处理。
> > 安卓模拟器-.Pixel_2_API_34_5554.2023-08-29.16-13-59.mp4
> 
> 对我来说同样的问题，你找到任何解决方案了吗？

https://github.com/jonataslaw/getx/issues/2883#issuecomment-1698689602

**Comment by AlexSmirnov9107** [comment]
@jonataslaw 
When do you plan an update 4.6.5 version to fix this?

**Comment by LianYangCn** [comment]
> Moving to master, the navigation's animation became very slow.
> 
>  Android.Emulator.-.Pixel_2_API_34_5554.2023-08-29.16-12-18.mp4 
> compared to before, but with the controller not disposing on page close.
> 
>  Android.Emulator.-.Pixel_2_API_34_5554.2023-08-29.16-13-59.mp4

Please set `defaultTransition`

```
return GetMaterialApp(
      ...,
      defaultTransition: Transition.native,
    );
```

**Comment by irfnyas** [comment]
> ![image](https://user-images.githubusercontent.com/41244714/264271918-c57d46ac-d04d-4de7-b462-2174125fe00c.png) Temporarily commenting these two lines of code solves this problem

For anyone need this hotfix for 4.6.5 feel free to use mine,

```
  get:
    git:
      url: https://github.com/irfnyas/getx.git
```

or if you use 4.6.1,
```
  get:
    git:
      url: https://github.com/irfnyas/getx.git
      ref: 4.6.1
```

**Comment by gauravmehta13** [comment]
i think the 4.6.5 version on github is not up to date with pub dev version, since there are several issues with the git version

**Comment by irfnyas** [comment]
> i think the 4.6.5 version on github is not up to date with pub dev version, since there are several issues with the git version

but it has the same pub upload and last commit date, May 22 2022. i'm open to suggestion if you have a better idea @gauravmehta13

**Comment by gauravmehta13** [comment]
> b upload and last commit date, May 22 2022. i'm open to suggestion if you have a

Yes, but not sure why the code isnt same, for me there are several breaking changes when using github version.

**Comment by gauravmehta13** [comment]
@irfnyas I got the issue, seems like [this](https://github.com/irfnyas/getx/commit/9d2b87242aa5d5b54aebd4d635d1e16835635c49) commit is extra and should not be included in v4.6.5 since these changes are not present on pub dev version.

Can you please remove this commit and update your repo.

**Comment by wph144** [comment]
> 4.6.1


I was originally using version 4.6.5.

Without "ref" -> The pubspec.lock pointed to HEAD and fetched "5.0.0-beta.30". I encountered a compilation error related to navigation (due to a breaking change where the binding parameter disappeared from the GetPage method), but I managed to fix it. However, I quickly rolled back because of severe bugs with the Android back button and route navigation.
With "ref: 4.6.1" -> It works perfectly.

**Comment by wph144** [comment]
> > ![image](https://user-images.githubusercontent.com/41244714/264271918-c57d46ac-d04d-4de7-b462-2174125fe00c.png) Temporarily commenting these two lines of code solves this problem
> 
> For anyone need this hotfix for 4.6.5 feel free to use mine,
> 
> ```
>   get:
>     git:
>       url: https://github.com/irfnyas/getx.git
> ```
> 
> or if you use 4.6.1,
> 
> ```
>   get:
>     git:
>       url: https://github.com/irfnyas/getx.git
>       ref: 4.6.1
> ```
> 
> Credit to [M1sakii](https://github.com/M1sakii) for the solution, thanks

I was originally using version 4.6.5.

Without "ref" -> The pubspec.lock pointed to HEAD and fetched "5.0.0-beta.30". I encountered a compilation error related to navigation (due to a breaking change where the binding parameter disappeared from the GetPage method), but I managed to fix it. However, I quickly rolled back because of severe bugs with the Android back button and route navigation.
With "ref: 4.6.1" -> It works perfectly.

**Comment by wph144** [comment]
Use this. 

  get:
    git:
      url: https://github.com/wph144/getx.git
      ref: 4.6.1-hotfix

**Comment by disonwei** [comment]
> 

dependencies: 
  cupertino_icons: ^1.0.5
  get:
    git:
      url: https://github.com/wph144/getx.git
      ref: 4.6.1-hotfix

I used  get_storage: ^2.1.1 , but there was a conflict.     

 Because get_storage 2.1.1 depends on get >=4.0.0 <6.0.0 and no versions of get_storage match >2.1.1 <3.0.0, get_storage ^2.1.1 requires get from hosted.
So, because suixinji depends on both get from git and get_storage ^2.1.1, version solving failed.

**Comment by zhangruiyu** [comment]
@jonataslaw

**Comment by jonataslaw** [comment]
I tried send the fix to the version 4.6.6
Please, check if it works for you (the code of 4.6.6 is a way different of version 5, I just remove the postframeCallback from routeDispose)

**Comment by kelpo123** [comment]
not working on 4.6.6 still issue
